# Generated by Django 2.2.16 on 2020-10-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20201004_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PrivatBank'), (2, 'MonoBank'), (3, 'vkurse'), (4, 'Ukrsibbank'), (5, 'Aval'), (6, 'Oschadbank')]),
        ),
    ]
