# Generated by Django 2.2.16 on 2020-12-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_auto_20201011_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USD'), (2, 'EUR')], db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='rate',
            index_together={('currency', 'source')},
        ),
    ]
