# Generated by Django 2.2.16 on 2020-12-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_auto_20201205_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'permissions': [('full_edit', 'This permissions allows user to update all available fields in Rate model')]},
        ),
    ]
